products:
  - id: kmipt-camp-winter-math-2026
    brand: kmipt
    title: "Зимняя ФизМат и IT школа KMIPT 2026"
    url: "https://kmipt.ru/courses/Zimnyaya_shkola/"
    category: camp
    grade_min: 5
    grade_max: 11
    subjects:
      - math
      - physics
      - informatics
    format: offline
    sessions:
      - name: "Зимняя смена"
        start_date: "2026-01-02"
        end_date: "2026-01-09"
        price_rub: 88200
    usp:
      - "Выездной интенсив с предметными треками"
      - "Подходит для школьников 5-11 классов"
      - "Данные по цене взяты с публичной страницы, уточняются перед оплатой"

  - id: kmipt-camp-summer-stem-2026
    brand: kmipt
    title: "Летняя выездная школа KMIPT 2026"
    url: "https://kmipt.ru/courses/Letnyaya_shkola/"
    category: camp
    grade_min: 5
    grade_max: 11
    subjects:
      - math
      - physics
      - informatics
    format: offline
    sessions:
      - name: "Летняя смена"
        start_date: "2026-06-20"
        end_date: "2026-07-03"
        price_rub: 83300
    usp:
      - "Выездной формат с учебной и проектной программой"
      - "Для учеников с разным уровнем подготовки"
      - "Итоговая стоимость и смена подтверждаются менеджером"

  - id: kmipt-ege-math-pro
    brand: kmipt
    title: "Подготовка к ЕГЭ по математике"
    url: "https://kmipt.ru/courses/EGE/matematika_ege/"
    category: ege
    grade_min: 10
    grade_max: 11
    subjects:
      - math
    format: hybrid
    sessions:
      - name: "Учебный год 2025/2026"
        start_date: "2025-09-01"
        end_date: "2026-05-31"
        price_rub: 82000
    usp:
      - "Годовой трек подготовки к ЕГЭ"
      - "Семестровый и годовой форматы обучения"
      - "Есть офлайн и онлайн варианты"

  - id: kmipt-ege-physics-pro
    brand: kmipt
    title: "Подготовка к ЕГЭ по физике"
    url: "https://kmipt.ru/courses/EGE/fizika_ege/"
    category: ege
    grade_min: 10
    grade_max: 11
    subjects:
      - physics
    format: hybrid
    sessions:
      - name: "Учебный год 2025/2026"
        start_date: "2025-09-01"
        end_date: "2026-05-31"
        price_rub: 82000
    usp:
      - "Системная подготовка под формат ЕГЭ"
      - "Есть выбор семестр/год"
      - "Поддержка в офлайн и онлайн форматах"

  - id: kmipt-ege-informatics-pro
    brand: kmipt
    title: "Подготовка к ЕГЭ по информатике"
    url: "https://kmipt.ru/courses/EGE/informatika_ege/"
    category: ege
    grade_min: 10
    grade_max: 11
    subjects:
      - informatics
    format: hybrid
    sessions:
      - name: "Учебный год 2025/2026"
        start_date: "2025-09-01"
        end_date: "2026-05-31"
        price_rub: 82000
    usp:
      - "Фокус на экзаменационных задачах и алгоритмах"
      - "Гибкий формат обучения"
      - "Стоимость подтверждается на странице записи"

  - id: kmipt-oge-math-start
    brand: kmipt
    title: "Подготовка к ОГЭ по математике"
    url: "https://kmipt.ru/courses/9_klass/matematika_9/"
    category: oge
    grade_min: 8
    grade_max: 9
    subjects:
      - math
    format: hybrid
    sessions:
      - name: "Учебный год 2025/2026"
        start_date: "2025-09-01"
        end_date: "2026-05-31"
        price_rub: 82000
    usp:
      - "Подготовка под структуру ОГЭ"
      - "Для 8-9 классов"
      - "Регулярные контрольные точки"

  - id: kmipt-oge-physics-start
    brand: kmipt
    title: "Подготовка к ОГЭ по физике"
    url: "https://kmipt.ru/courses/9_klass/fizika_9/"
    category: oge
    grade_min: 8
    grade_max: 9
    subjects:
      - physics
    format: hybrid
    sessions:
      - name: "Учебный год 2025/2026"
        start_date: "2025-09-01"
        end_date: "2026-05-31"
        price_rub: 82000
    usp:
      - "Охват всей школьной базы для ОГЭ"
      - "Офлайн и онлайн обучение"
      - "Стоимость уточняется по действующему прайсу"

  - id: kmipt-oge-informatics-start
    brand: kmipt
    title: "Подготовка к ОГЭ по информатике"
    url: "https://kmipt.ru/courses/9_klass/informatika_9/"
    category: oge
    grade_min: 8
    grade_max: 9
    subjects:
      - informatics
    format: hybrid
    sessions:
      - name: "Учебный год 2025/2026"
        start_date: "2025-09-01"
        end_date: "2026-05-31"
        price_rub: 82000
    usp:
      - "Пошаговая подготовка к экзамену"
      - "Тренировка в экзаменационном формате"
      - "Есть онлайн формат"

  - id: kmipt-olymp-math-8-11
    brand: kmipt
    title: "Олимпиадная математика"
    url: "https://kmipt.ru/courses/olimpiads/olimpiad_matematika/"
    category: olympiad
    grade_min: 8
    grade_max: 11
    subjects:
      - math
    format: hybrid
    usp:
      - "Подготовка к олимпиадным этапам"
      - "Разбор сложных нестандартных задач"
      - "Индивидуальная траектория в группе"

  - id: kmipt-olymp-physics-8-11
    brand: kmipt
    title: "Олимпиадная физика"
    url: "https://kmipt.ru/courses/olimpiads/olimpiad_fizika/"
    category: olympiad
    grade_min: 8
    grade_max: 11
    subjects:
      - physics
    format: hybrid
    usp:
      - "Развитие олимпиадного мышления"
      - "Подготовка к задачам повышенной сложности"
      - "Формат офлайн и онлайн"

  - id: kmipt-base-math-5-8
    brand: kmipt
    title: "Математика 5-8 класс"
    url: "https://kmipt.ru/courses/5_8_klass/matematika_5_8/"
    category: base
    grade_min: 5
    grade_max: 8
    subjects:
      - math
    format: hybrid
    sessions:
      - name: "Учебный год 2025/2026"
        start_date: "2025-09-01"
        end_date: "2026-05-31"
        price_rub: 82000
    usp:
      - "Углубленное изучение школьной программы"
      - "Устранение пробелов и развитие базы"
      - "Доступен выбор формата"

  - id: kmipt-base-informatics-5-8
    brand: kmipt
    title: "Информатика 5-8 класс"
    url: "https://kmipt.ru/courses/5_8_klass/informatika_5_8/"
    category: base
    grade_min: 5
    grade_max: 8
    subjects:
      - informatics
    format: hybrid
    sessions:
      - name: "Учебный год 2025/2026"
        start_date: "2025-09-01"
        end_date: "2026-05-31"
        price_rub: 82000
    usp:
      - "Основа программирования и алгоритмов"
      - "Подходит для старта и систематизации"
      - "Гибридный формат обучения"

  - id: foton-camp-winter-2026
    brand: foton
    title: "Зимняя выездная ФизМат и IT школа ФОТОН 2026"
    url: "https://cdpofoton.ru/courses/zimnyaya-shkola-2026/"
    category: camp
    grade_min: 5
    grade_max: 11
    subjects:
      - math
      - physics
      - informatics
    format: offline
    sessions:
      - name: "Зимняя смена"
        start_date: "2026-01-02"
        end_date: "2026-01-09"
        price_rub: 58900
    usp:
      - "Выездная школа с предметными треками"
      - "Комбинация обучения и командных активностей"
      - "Цена по публичной карточке, финальные условия подтверждает менеджер"

  - id: foton-camp-summer-2026
    brand: foton
    title: "Летняя выездная школа ФОТОН 2026"
    url: "https://cdpofoton.ru/courses/letnyaya-shkola-2026/"
    category: camp
    grade_min: 5
    grade_max: 10
    subjects:
      - math
      - physics
      - informatics
    format: offline
    sessions:
      - name: "Летняя смена"
        start_date: "2026-06-20"
        end_date: "2026-07-03"
        price_rub: 68900
    usp:
      - "Выездной формат для 5-10 классов"
      - "Упор на предметную прокачку и мотивацию"
      - "Параметры смены уточняются перед бронированием"

  - id: foton-ege-math
    brand: foton
    title: "Подготовка к ЕГЭ по математике (ФОТОН)"
    url: "https://cdpofoton.ru/courses/podgotovka-k-ege-po-matematike/"
    category: ege
    grade_min: 10
    grade_max: 11
    subjects:
      - math
    format: hybrid
    usp:
      - "Подготовка к ЕГЭ 10-11 класс"
      - "Возможны разные форматы участия"
      - "Стоимость на сайте указана от базового тарифа"

  - id: foton-ege-physics
    brand: foton
    title: "Подготовка к ЕГЭ по физике (ФОТОН)"
    url: "https://cdpofoton.ru/courses/podgotovka-k-ege-po-fizike/"
    category: ege
    grade_min: 10
    grade_max: 11
    subjects:
      - physics
    format: hybrid
    usp:
      - "ЕГЭ-трек для 10-11 классов"
      - "Фокус на экзаменационных задачах"
      - "Точные тарифы подтверждаются менеджером"

  - id: foton-ege-informatics
    brand: foton
    title: "Подготовка к ЕГЭ по информатике (ФОТОН)"
    url: "https://cdpofoton.ru/courses/podgotovka-k-ege-po-informatike/"
    category: ege
    grade_min: 10
    grade_max: 11
    subjects:
      - informatics
    format: hybrid
    usp:
      - "Подготовка к задачам ЕГЭ по информатике"
      - "Подходит для учеников 10-11 классов"
      - "Актуальные условия указываются при записи"

  - id: foton-oge-math
    brand: foton
    title: "Подготовка к ОГЭ по математике (ФОТОН)"
    url: "https://cdpofoton.ru/courses/podgotovka-k-oge-po-matematike/"
    category: oge
    grade_min: 8
    grade_max: 9
    subjects:
      - math
    format: hybrid
    usp:
      - "ОГЭ-трек для 8-9 классов"
      - "Системный разбор тем и практики"
      - "Тарифы и расписание подтверждаются перед стартом"

  - id: foton-oge-physics
    brand: foton
    title: "Подготовка к ОГЭ по физике (ФОТОН)"
    url: "https://cdpofoton.ru/courses/podgotovka-k-oge-po-fizike/"
    category: oge
    grade_min: 8
    grade_max: 9
    subjects:
      - physics
    format: hybrid
    usp:
      - "Подготовка по ключевым темам ОГЭ"
      - "Для учеников 8-9 классов"
      - "Есть очный и дистанционный формат"

  - id: foton-oge-informatics
    brand: foton
    title: "Подготовка к ОГЭ по информатике (ФОТОН)"
    url: "https://cdpofoton.ru/courses/podgotovka-k-oge-po-informatike/"
    category: oge
    grade_min: 8
    grade_max: 9
    subjects:
      - informatics
    format: hybrid
    usp:
      - "Подготовка к формату экзамена"
      - "Тренировка типовых заданий"
      - "Актуальные условия по запросу"

  - id: foton-olymp-math-8-11
    brand: foton
    title: "Подготовка к олимпиадам по математике (ФОТОН)"
    url: "https://cdpofoton.ru/courses/podgotovka-k-olimpiadam-po-matematike/"
    category: olympiad
    grade_min: 8
    grade_max: 11
    subjects:
      - math
    format: hybrid
    usp:
      - "Олимпиадные треки для 8-11 классов"
      - "Разбор нестандартных задач"
      - "Подготовка к этапам олимпиад"

  - id: foton-olymp-physics-8-11
    brand: foton
    title: "Подготовка к олимпиадам по физике (ФОТОН)"
    url: "https://cdpofoton.ru/courses/podgotovka-k-olimpiadam-po-fizike/"
    category: olympiad
    grade_min: 8
    grade_max: 11
    subjects:
      - physics
    format: hybrid
    usp:
      - "Предметная олимпиадная подготовка"
      - "Развитие аналитического мышления"
      - "Группы по уровню"

  - id: foton-olymp-informatics-8-11
    brand: foton
    title: "Подготовка к олимпиадам по информатике (ФОТОН)"
    url: "https://cdpofoton.ru/courses/podgotovka-k-olimpiadam-po-informatike/"
    category: olympiad
    grade_min: 8
    grade_max: 11
    subjects:
      - informatics
    format: hybrid
    usp:
      - "Алгоритмы и олимпиадные задачи"
      - "Подготовка к соревнованиям и этапам"
      - "Форматы обучения зависят от потока"

  - id: foton-base-math-5-8
    brand: foton
    title: "Углубленное изучение математики 5-8 класс (ФОТОН)"
    url: "https://cdpofoton.ru/courses/uglublyonnoe-izuchenie-matematiki-5-8-k/"
    category: base
    grade_min: 5
    grade_max: 8
    subjects:
      - math
    format: hybrid
    usp:
      - "Усиление школьной базы по математике"
      - "Подходит для регулярной работы в течение года"
      - "Стоимость стартует от базового тарифа"

  - id: foton-base-physics-5-8
    brand: foton
    title: "Углубленное изучение физики 5-8 класс (ФОТОН)"
    url: "https://cdpofoton.ru/courses/uglublyonnoe-izuchenie-fiziki-5-8-k/"
    category: base
    grade_min: 5
    grade_max: 8
    subjects:
      - physics
    format: hybrid
    usp:
      - "Физика для системной школьной подготовки"
      - "Наращивание предметной уверенности"
      - "Формат и расписание подтверждаются по потоку"

  - id: foton-base-informatics-5-8
    brand: foton
    title: "Программирование для 5-8 классов (ФОТОН)"
    url: "https://cdpofoton.ru/courses/programmirovanie-dlya-5-8-k/"
    category: base
    grade_min: 5
    grade_max: 8
    subjects:
      - informatics
    format: hybrid
    usp:
      - "Базовый трек программирования для школьников"
      - "Практика и развитие алгоритмического мышления"
      - "Актуальные условия доступны при записи"

  - id: foton-online-courses-9-11
    brand: foton
    title: "Онлайн-курсы 9-11 классы (ФОТОН)"
    url: "https://cdpofoton.ru/courses/online-kursy-9-11/"
    category: intensive
    grade_min: 9
    grade_max: 11
    subjects:
      - math
      - physics
      - informatics
    format: online
    sessions:
      - name: "Семестр"
        start_date: "2025-09-01"
        end_date: "2026-01-31"
        price_rub: 36700
      - name: "Год"
        start_date: "2025-09-01"
        end_date: "2026-05-31"
        price_rub: 71400
    usp:
      - "Онлайн-формат для 9-11 классов"
      - "Есть семестровый и годовой тариф"
      - "Стоимость взята с публичной страницы онлайн-курсов"
