products:
- id: kmipt-courses-nabor_online-olimp_math_phys
  brand: kmipt
  title: Подготовка к олимпиадам по математике и физике очно
  url: https://kmipt.ru/courses/nabor_online/olimp_math_phys/
  category: olympiad
  grade_min: 5
  grade_max: 11
  subjects:
  - math
  - physics
  format: offline
  sessions: []
  usp:
  - Преподаватели МФТИ, члены жюри олимпиад помогут стать победителем олимпиад по
    Математике и Физике. Эффективнее чем репетитор. От 600р/час. Записывайся сейчас!
  - Подходит для 5-11 классов
  - Данные собраны автоматически с публичного сайта, нужна ручная проверка
- id: kmipt-courses-ege-matematika_ege
  brand: kmipt
  title: Математика ЕГЭ
  url: https://kmipt.ru/courses/EGE/Matematika_EGE/
  category: ege
  grade_min: 10
  grade_max: 11
  subjects:
  - math
  format: offline
  sessions: []
  usp:
  - Преподаватели - эксперты ЕГЭ и олимпиад помогут успешно сдать ЕГЭ 2025 по Профильной
    Математике. Мини-группы 7-9 человек. Лучше чем репетитор. От 500р/час. Записывайся
    сейчас!
  - Подходит для 10-11 классов
  - Данные собраны автоматически с публичного сайта, нужна ручная проверка
- id: kmipt-courses-ege-fizika_ege
  brand: kmipt
  title: Физика ЕГЭ
  url: https://kmipt.ru/courses/EGE/Fizika_EGE/
  category: ege
  grade_min: 10
  grade_max: 11
  subjects:
  - physics
  format: offline
  sessions: []
  usp:
  - Преподаватели - эксперты ЕГЭ и олимпиад помогут успешно сдать ЕГЭ 2025 по Физике.
    Мини-группы 7-9 человек. Удобное место и время занятий. От 500р/час. Записывайся
    сейчас!
  - Подходит для 10-11 классов
  - Данные собраны автоматически с публичного сайта, нужна ручная проверка
- id: kmipt-courses-ege-informatika_ege
  brand: kmipt
  title: Информатика ЕГЭ
  url: https://kmipt.ru/courses/EGE/Informatika_EGE/
  category: ege
  grade_min: 10
  grade_max: 11
  subjects:
  - informatics
  format: offline
  sessions: []
  usp:
  - Преподаватели - эксперты ЕГЭ и олимпиад помогут успешно сдать ЕГЭ 2025 по Информатике.
    Мини-группы 7-9 человек. Удобное место и время занятий. От 500р/час. Записывайся
    сейчас!
  - Подходит для 10-11 классов
  - Данные собраны автоматически с публичного сайта, нужна ручная проверка
- id: kmipt-courses-ege-russkiy_yazyk_ege
  brand: kmipt
  title: Русский язык ЕГЭ
  url: https://kmipt.ru/courses/EGE/Russkiy_yazyk_EGE/
  category: ege
  grade_min: 10
  grade_max: 11
  subjects:
  - russian
  format: offline
  sessions: []
  usp:
  - Лингвисты и эксперты ЕГЭ и олимпиад помогут успешно сдать ЕГЭ. Мини-группы 7-9
    человек. Более 25 лет в сфере образования. Лучше чем репетитор. От 600р/час. Записывайся
    сейчас!
  - Подходит для 10-11 классов
  - Данные собраны автоматически с публичного сайта, нужна ручная проверка
- id: kmipt-courses-zhukovskiy-ochnie
  brand: kmipt
  title: Очные курсы по математике, физике, информатике и русскому языку в г. Жуковский
  url: https://kmipt.ru/courses/zhukovskiy/ochnie/
  category: base
  grade_min: 5
  grade_max: 11
  subjects:
  - math
  - physics
  - informatics
  - russian
  format: offline
  sessions: []
  usp:
  - УНПК МФТИ объявляет набор на 2025-2026 год! Подготовка к ЕГЭ, ОГЭ и Олимпиадам
    с преподавателями МГУ и МФТИ! Звони и записывайся!
  - Подходит для 5-11 классов
  - Данные собраны автоматически с публичного сайта, нужна ручная проверка
- id: kmipt-courses-ege_10-ege_matematika_10
  brand: kmipt
  title: Математика 10 класс
  url: https://kmipt.ru/courses/EGE_10/EGE_Matematika_10/
  category: ege
  grade_min: 10
  grade_max: 10
  subjects:
  - math
  format: offline
  sessions: []
  usp:
  - Преподаватели - эксперты ЕГЭ и олимпиад подготовят к сдаче ЕГЭ по Математике.
    Углубленный курс на 2 года. Мини-группы. Эффективнее чем репетитор. От 600р/час.
    Записывайся!
  - Подходит для 10-10 классов
  - Данные собраны автоматически с публичного сайта, нужна ручная проверка
- id: kmipt-courses-ege_10-fizika_10
  brand: kmipt
  title: Физика 10 класс
  url: https://kmipt.ru/courses/EGE_10/Fizika_10/
  category: ege
  grade_min: 10
  grade_max: 10
  subjects:
  - physics
  format: offline
  sessions: []
  usp:
  - Преподаватели - эксперты ЕГЭ и олимпиад подготовят к сдаче ЕГЭ по Физике. Углубленный
    курс на 2 года. Мини-группы. Эффективнее чем репетитор. От 600р/час. Записывайся!
  - Подходит для 10-10 классов
  - Данные собраны автоматически с публичного сайта, нужна ручная проверка
- id: kmipt-courses-ege_10-informatika_10
  brand: kmipt
  title: Информатика 10 класс
  url: https://kmipt.ru/courses/EGE_10/Informatika_10/
  category: ege
  grade_min: 10
  grade_max: 10
  subjects:
  - informatics
  format: offline
  sessions: []
  usp:
  - Преподаватели - эксперты ЕГЭ и олимпиад подготовят к сдаче ЕГЭ по Информатике.
    Углубленный курс на 2 года. Мини-группы. Эффективнее чем репетитор. От 600р/час.
    Записывайся!
  - Подходит для 10-10 классов
  - Данные собраны автоматически с публичного сайта, нужна ручная проверка
